### ISSUE TITLE
UndefinedFunctionError Makeup.Lexers.ElixirLexer.lex/2

### ISSUE THREAD

**Issue by paridin** [tmbb/makeup#20]
```** (UndefinedFunctionError) function Makeup.Lexers.ElixirLexer.lex/2 is undefined (module Makeup.Lexers.ElixirLexer is not available)
    Makeup.Lexers.ElixirLexer.lex("%{}", [])
(makeup) lib/makeup.ex:41: Makeup.highlight/2
(web) lib/web/views/admin_view.ex:12: Web.AdminView.elixir_code_html/1
```

I'm having the previous error when I deployed. 

```
defp deps do
   ...,
   {:makeup, "~> 0.8"}
end
```

I tested the lexer's but didn't work my last lexer was html5.

```
def elixir_code_html(map) when is_map(map) do
    {:safe, Makeup.highlight("#{inspect(map, pretty: true)}", name: "html5")}
end
```

**Comment by axelson** [comment]
@paridin you need to add `:makeup_elixir` to your deps in order to get the Elixir lexer (which is required for most operations)
